-- ====================================================================
-- Online Book Store Analysis
-- Author : Nithin Vandana
-- Database : Online Book Store
-- ==================================================================

-- RETREIVE ALL BOOKS FROM THE BOOKS TABLE
SELECT * FROM books;

-- Show all customers from a specific country.
SELECT * FROM customers where country = 'India';

-- find all books belonging to the fiction genre
SELECT * FROM books WHERE genre = 'Fiction';

-- Display books published after 2000.
SELECT * FROM books WHERE published_year = 2000;

-- Find the price of the most expensive book.
SELECT title, MAX(price) as expensive_price FROM books
GROUP BY title
ORDER BY MAX(price) DESC
LIMIT 1;

-- Find the price of the cheapest book.
SELECT * FROM books 
ORDER BY price
LIMIT 1; 

-- Count the total number of books
SELECT COUNT(book_id) AS No_of_books FROM books;

-- Count the total number of customers.
SELECT COUNT(customer_id) as No_Of_Customers FROM customers;

-- Count the total number of orders
SELECT COUNT(order_id) AS No_Of_Orders FROM orders;

-- List all unique genres
SELECT DISTINCT genre FROM books;

-- find the average price of books
SELECT COALESCE(AVG(price),0) AVG_PRICE FROM books;

-- FIND THE TOTAL STOCK AVAILABLE
SELECT SUM(stock) AS TOTAL_STOCK FROM books;

-- FIND THE MAX STOCK AVAILABLE FOR A BOOK
SELECT 
    MAX(stock) as Maximum_stock 
FROM books;

-- FIND THE MIN STOCK AVAILABLE FOR A BOOK
SELECT 
    MIN(stock) as Minimum_stock 
FROM books;

-- COUNT BOOKS IN EACH GENRE
SELECT genre, COUNT(book_id) as no_of_books
FROM books GROUP BY genre;

-- find the average book price by genre
SELECT genre, ROUND(AVG(price),3)AS AVG_PRICE
FROM books GROUP BY genre;

-- FIND THE NO OF CUSTOMERS IN EACH COUNTRY
SELECT country, COUNT(customer_id) AS no_of_customers
FROM  customers GROUP BY country ORDER BY no_of_customers DESC;

-- FIND THE TOTAL SALES AMOUNT GENERATED
SELECT SUM(total_amount) AS total_sales_amount FROM orders;

-- find the average order value
SELECT AVG(total_amount) FROM orders;

-- find the highest order amount
SELECT MAX(total_amount) AS TOTAL_AMOUNT FROM orders;

-- DISPLAY CUSTOMER NAMES ALONG WITH THEIR ORDERS
SELECT * FROM customers;
SELECT * FROM orders;

SELECT c.customer_id, o.order_id, c.name, o.book_id
FROM customers as c
JOIN orders AS o
ON c.customer_id = o.customer_id;

-- display book titles along with their order quantity
SELECT b.book_id, b.title, b.author, o.quantity
FROM books b
JOIN orders o
ON b.book_id = o.book_id;

-- show all orders with customers name and book title
SELECT o.*, c.name, b.title
FROM books as b
JOIN orders as o
	ON o.book_id = b.book_id
JOIN customers c
	ON c.customer_id = o.customer_id;

-- find all books ordered by a particular customer
SELECT c.customer_id, c.name, b.*
FROM customers as c
JOIN orders as o
	ON c.customer_id = o.customer_id
JOIN books as b
	ON b.book_id = o.book_id
WHERE c.customer_id = 101;

-- find customers who ordered books from the fantasy genre
SELECT * FROM orders;
SELECT * FROM books;
SELECT * FROM customers;
SELECT c.customer_id, o.order_id, c.name, b.genre
FROM books as b
JOIN orders as o
ON o.book_id = b.book_id
JOIN customers as c
ON c.customer_id = o.customer_id
WHERE b.genre = 'Fantasy';

-- find books purchased by customers from a specific country
SELECT b.book_id, b.title, c.name, c.country
FROM books as b
JOIN orders as o
	ON o.book_id = b.book_id
JOIN customers as c
	ON c.customer_id = o.customer_id
WHERE country = 'China';

-- show order details with title, customer name, quantity, and amount
SELECT o.order_id, o.book_id, o.order_date, 
	b.title, c.name, o.quantity, o.total_amount
FROM orders as o
JOIN books as b
	ON o.book_id = b.book_id
JOIN customers as c
	ON c.customer_id = o.customer_id;
    
-- find total books sold by each customer
SELECT c.customer_id, c.name, SUM(quantity) as TOTAL_QUANTITY
FROM customers as c
JOIN orders as o
	ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name;

-- FIND THE TOTAL REVENUE GENERATED BY EACH BOOK
SELECT b.book_id, ROUND(SUM(b.price * o.quantity),4) as Total_Revenue
FROM orders as o
JOIN books as b
	ON o.book_id = b.book_id
GROUP BY b.book_id;

-- find total revenue generated by each genre
SELECT b.genre, ROUND(SUM(b.price * o.quantity),4) as Total_Revenue
FROM orders as o
JOIN books as b
	ON o.book_id = b.book_id
GROUP BY b.genre
ORDER BY Total_Revenue DESC;

-- find the top 10 customers by spending
SELECT * FROM orders;
SELECT * FROM customers;
SELECT * FROM books;

SELECT c.customer_id, c.name,
ROUND(SUM(o.total_amount),3) as total_spending
FROM customers c
JOIN orders as o
ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spending DESC
LIMIT 10;

-- FIND THE TOP 10 BEST SELLING BOOKS
SELECT b.book_id, b.title, SUM(o.quantity) AS Top_books_sold
FROM books as b
JOIN orders as o
ON b.book_id = o.book_id
GROUP BY b.book_id, b.title 
ORDER BY Top_books_sold
LIMIT 10;
SELECT DISTINCT quantity FROM orders;

-- find the top 5 genre by revenue
SELECT * FROM orders;
SELECT * FROM customers;
SELECT * FROM books;

SELECT ROUND(SUM(o.total_amount),3) AS REVENUE, b.genre
FROM books as b
JOIN orders as o
	ON o.book_id = b.book_id
GROUP BY b.genre
ORDER BY REVENUE DESC
LIMIT 5;

-- FIND THE MOST FREQUENTLY ORDERED BOOK
SELECT b.book_id, b.title, COUNT(o.book_id) as No_Of_times
FROM books as b
JOIN orders as o
ON o.book_id = b.book_id
GROUP BY b.book_id, b.title
ORDER BY No_Of_times DESC;

-- FIND THE CUSTOMERS WHO PLACED THE MOST ORDERS
SELECT c.customer_id, c.name, COUNT(o.order_id) AS no_of_orders
FROM orders as o
JOIN customers as c
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY no_of_orders DESC
LIMIT 1;

-- FIND THE COUNTRY GENERATING THE HIGHEST REVENUE
SELECT c.country, SUM(o.total_amount) AS total_revenue
FROM customers as c
JOIN orders as o
ON c.customer_id = o.customer_id
JOIN books as b
ON b.book_id = o.book_id
GROUP BY c.country
ORDER BY total_revenue DESC
LIMIT 1;

-- find the author whose books generated the most revenue
SELECT b.author, ROUND(SUM(o.total_amount),3) as total_revenue
FROM books as b
JOIN orders as o
ON o.book_id = b.book_id
GROUP BY b.author
ORDER BY total_revenue DESC
LIMIT 1;

-- find the average quantity ordered per order
SELECT  ROUND(AVG(quantity),2) AS AVG_QUANTITY
FROM orders;

-- find all books that have never been ordered
SELECT b.book_id, b.title, b.author, b.genre
FROM books as b
LEFT JOIN orders as o
ON o.book_id = b.book_id
WHERE order_id IS NULL;

-- FIND ALL CUSTOMERS WHO HAVE NEVER PLACED AN ORDER
SELECT  c.customer_id, c.name, c.city, c.country
FROM customers as c
LEFT JOIN orders as o
ON c.customer_id = o.customer_id 
WHERE o.customer_id IS NULL;

-- FIND ALL BOOKS WHOSE TOTAL SALES QUANTITY IS 
-- GREATER THAN THE AVERAGE SALES QUANTITY OF ALL BOOKS
SELECT b.book_id, b.author, 
SUM(o.quantity) AS total_sales_quantity
FROM books as b
JOIN orders as o
ON o.book_id = b.book_id
GROUP BY b.book_id, b.author
HAVING SUM(o.quantity) > 
	(SELECT AVG(o.quantity) as AVG_SALES_QUANTITY FROM orders as o);
    
-- FIND ALL CUSTOMERS WHOSE TOTAL SPENDING IS 
-- GREATER THAN THE AVERAGE SPENDING OF ALL CUSTOMERS
SELECT c.customer_id, c.name, ROUND(SUM(o.total_amount),2) as TOTAL_SPENDING
FROM customers as c
LEFT JOIN orders as o
	ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
HAVING SUM(o.Total_Amount) > 
	(SELECT AVG(customer_spending) FROM 
		(SELECT customer_id, SUM(total_amount) AS customer_spending
		 FROM orders GROUP BY customer_id) t
     );

-- find the second highest spending customer
SELECT c.customer_id, c.name, ROUND(SUM(o.total_amount),2) AS total_spending
FROM customers as c
JOIN orders as o
ON c.customer_id = o.customer_id
GROUP BY c.Customer_ID, c.name
ORDER BY total_spending DESC 
LIMIT 1 OFFSET 1;

-- FIND THE THIRD REVENUE-GENERATION BOOK
SELECT * FROM 
(SELECT b.book_id, b.title, ROUND(SUM(b.price * o.quantity),3) as 3rd_total_revenue
FROM customers as c
JOIN orders as O
ON c.customer_id = o.customer_id
JOIN books as b
ON b.book_id = o.book_id
GROUP BY b.book_id, b.title
ORDER BY 3rd_total_revenue DESC
LIMIT 1 OFFSET 2) t
ORDER BY 3rd_total_revenue
LIMIT 1;

-- FIND ALL CUSTOMERS WHO HAVE PURCHASED BOOKS FROM MORE THAN 3 DIFFERENT GENRES
SELECT c.customer_id, c.name, COUNT(DISTINCT b.genre) as genres
FROM customers as c
JOIN orders as o
ON c.Customer_ID = o.Customer_ID
JOIN books as b
ON b.book_id = o.book_id
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT b.genre) > 3
ORDER BY genres DESC;

-- FIND THE PERCENTAGE CONTRIBUTION OF EACH GENERE TO THE TOTAL REVENUE
SELECT b.genre, 
round(SUM(b.price * o.Quantity),2) as Total_revenue,
ROUND(PERCENT_RANK() 
	OVER(
     ORDER BY b.genre),2) as Percentage_caluculation
FROM books as b
JOIN orders as o
ON o.book_id = b.book_id
GROUP BY b.genre;

-- ANOTHER METHOD 
SELECT b.genre,
       ROUND(SUM(o.total_amount), 2) AS total_revenue,
       ROUND(
           (SUM(o.total_amount) /
           (SELECT SUM(o.total_amount) FROM orders as o)) * 100,
           2
       ) AS percentage_contribution
FROM books b
JOIN orders o
    ON o.book_id = b.book_id
GROUP BY b.genre;

-- FIND THE TOP 3 CUSTOMERS IN EACH COUNTRY BASED ON TOTAL SPENDING
SELECT *
FROM
(
    SELECT c.country,
           c.customer_id,
           c.name,
           ROUND(SUM(o.total_amount),2) AS total_spending,
           RANK() OVER(
               PARTITION BY c.country
               ORDER BY SUM(o.total_amount) DESC
           ) AS customer_rank
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.country, c.customer_id, c.name
) t
WHERE customer_rank <= 3;

-- FIND THE AUTHOR WHOSE BOOKS WERE 
-- PURCHASED BY THE HIGHEST NUMBER OF DISTINCT CUSTOMERS
SELECT 
	b.author, 
    COUNT(DISTINCT c.customer_id) as Unique_customers
FROM customers as c
JOIN orders as o
ON c.customer_id = o.customer_id
JOIN books as b
ON b.book_id = o.book_id
GROUP BY b.author
ORDER BY Unique_customers DESC
LIMIT 1;

-- FIND THE GENRE WITH THE HIGHEST AVERAGE BOOK PRICE
SELECT b.genre,
ROUND(AVG(b.price),2) AS AVG_PRICE
FROM books as b
GROUP BY b.genre
ORDER BY AVG_PRICE DESC
LIMIT 1;

-- FIND CUSTOMERS WHO PURCHASED AT LEAST ONE 
-- BOOK FROM EVERY GENRE AVAIALABLE IN THE BOOK STORE
SELECT c.Customer_ID, c.name,
COUNT(DISTINCT b.genre) as Unique_genre